// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace FileUpload.Models
{
  public class FilesOnDatabaseConfiguration : IEntityTypeConfiguration<FilesOnDatabase>
  {
    public void Configure(EntityTypeBuilder<FilesOnDatabase> entity)
    {
      entity.HasIndex(e => new { e.Name })
         .HasDatabaseName("IX_FileName");

      entity.HasIndex(e => new { e.Name })
         .HasDatabaseName("IX_Extension");

      entity.HasIndex(e => new { e.Name, e.FileType })
          .HasDatabaseName("IX_FileNameFileType")
          .IsUnique();

      entity.HasIndex(e => new { e.Name, e.Extension })
          .HasDatabaseName("IX_FileNameExtension")
          .IsUnique();

      //entity.HasData(new FilesOnDatabase
      //{
      //  Id = 1,
      //  Name = "test1",
      //  Extension = "txt",
      //  CreatedOn = DateTime.Today,
      //  FileType = "text",
      //  Description = "Test file1 on database"
      //});
      //entity.HasData(new FilesOnDatabase
      //{
      //  Id = 2,
      //  Name = "test2",
      //  Extension = "txt",
      //  CreatedOn = DateTime.Today,
      //  FileType = "text",
      //  Description = "Test file2 on database"
      //});
    }
  }
}
