// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace FileUpload.Models
{
  public class FilesOnFileSystemConfiguration : IEntityTypeConfiguration<FilesOnFileSystem>
  {
    public void Configure(EntityTypeBuilder<FilesOnFileSystem> entity)
    {
      entity.HasIndex(e => new { e.Name })
         .HasDatabaseName("IX_FileName");

      entity.HasIndex(e => new { e.Name })
         .HasDatabaseName("IX_Extension");

      entity.HasIndex(e => new { e.Name, e.FileType })
          .HasDatabaseName("IX_FileNameFileType")
          .IsUnique();

      entity.HasIndex(e => new { e.Name, e.Extension })
          .HasDatabaseName("IX_FileNameExtension")
          .IsUnique();

      //entity.HasData(new FilesOnFileSystem
      //{
      //  Id = 1,
      //  Name = "test1",
      //  Extension = "txt",
      //  FilePath = "c:\\users\\vhaporsunc\\download",
      //  FileType = "text"
      //});
      //entity.HasData(new FilesOnFileSystem
      //{
      //  Id = 2,
      //  Name = "test2",
      //  Extension = "txt",
      //  FilePath = "c:\\users\\vhaporsunc\\download",
      //  FileType = "text"
      //});
    }
  }
}
